export const dataPublicaciones = [
  {
    publicacionId: 1,
    usuarioId: 101,
    titulo: 'Servicio de electricidad',
    contenido: 'Ofrezco servicios eléctricos de alta calidad',
    imagen: 'imagen1.jpg',
    tiposervicio: 'electricidad',
    emailcontacto: 'usuario1@example.com',
    telefonocontacto: '+56 9 1234 5678',
    ciudad: 'Santiago',
    comuna: 'Providencia',
    fechapublicacion: '2024-02-24',
    likes: 15,
  },
  {
    publicacionId: 2,
    usuarioId: 102,
    titulo: 'Reparación de fontanería',
    contenido: 'Especializado en reparaciones de fontanería',
    imagen: 'imagen2.jpg',
    tiposervicio: 'gasfiteria',
    emailcontacto: 'usuario2@example.com',
    telefonocontacto: '+56 9 9876 5432',
    ciudad: 'Concepción',
    comuna: 'Talcahuano',
    fechapublicacion: '2024-02-23',
    likes: 20,
  },
  {
    publicacionId: 3,
    usuarioId: 103,
    titulo: 'Instalación de gas',
    contenido: 'Servicio de instalación y reparación de gas',
    imagen: 'imagen3.jpg',
    tiposervicio: 'gasfiteria',
    emailcontacto: 'usuario3@example.com',
    telefonocontacto: '+56 9 5555 5555',
    ciudad: 'Valparaíso',
    comuna: 'Viña del Mar',
    fechapublicacion: '2024-02-22',
    likes: 12,
  },
  {
    publicacionId: 4,
    usuarioId: 104,
    titulo: 'Reparación de electrodomésticos',
    contenido: 'Experto en reparación de electrodomésticos',
    imagen: 'imagen4.jpg',
    tiposervicio: 'electrodomesticos',
    emailcontacto: 'usuario4@example.com',
    telefonocontacto: '+56 9 1111 2222',
    ciudad: 'Antofagasta',
    comuna: 'Calama',
    fechapublicacion: '2024-02-21',
    likes: 18,
  },
  {
    publicacionId: 5,
    usuarioId: 105,
    titulo: 'Mantenimiento de calefacción',
    contenido: 'Ofrezco servicios de mantenimiento de calefacción',
    imagen: 'imagen5.jpg',
    tiposervicio: 'calefaccion',
    emailcontacto: 'usuario5@example.com',
    telefonocontacto: '+56 9 9999 8888',
    ciudad: 'Temuco',
    comuna: 'Padre Las Casas',
    fechapublicacion: '2024-02-20',
    likes: 25,
  },
  {
    publicacionId: 6,
    usuarioId: 106,
    titulo: 'Construcción y remodelación',
    contenido: 'Realizo trabajos de construcción y remodelación',
    imagen: 'imagen6.jpg',
    tiposervicio: 'construccion',
    emailcontacto: 'usuario6@example.com',
    telefonocontacto: '+56 9 3333 4444',
    ciudad: 'Rancagua',
    comuna: 'Machalí',
    fechapublicacion: '2024-02-19',
    likes: 22,
  },
  {
    publicacionId: 7,
    usuarioId: 107,
    titulo: 'Pintura y decoración',
    contenido: 'Servicio de pintura y decoración de interiores',
    imagen: 'imagen7.jpg',
    tiposervicio: 'pintura',
    emailcontacto: 'usuario7@example.com',
    telefonocontacto: '+56 9 7777 6666',
    ciudad: 'Iquique',
    comuna: 'Alto Hospicio',
    fechapublicacion: '2024-02-18',
    likes: 17,
  },
  {
    publicacionId: 8,
    usuarioId: 108,
    titulo: 'Servicio de jardinería',
    contenido: 'Mantenimiento de jardines y diseño paisajístico',
    imagen: 'imagen8.jpg',
    tiposervicio: 'jardineria',
    emailcontacto: 'usuario8@example.com',
    telefonocontacto: '+56 9 8888 9999',
    ciudad: 'La Serena',
    comuna: 'Coquimbo',
    fechapublicacion: '2024-02-17',
    likes: 14,
  },
  // {
  //   publicacionId: 9,
  //   usuarioId: 109,
  //   titulo: "Reparación de computadoras",
  //   contenido: "Especializado en reparación de computadoras",
  //   imagen: "imagen9.jpg",
  //   tiposervicio: "informatica",
  //   emailcontacto: "usuario9@example.com",
  //   telefonocontacto: "+56 9 6666 7777",
  //   ciudad: "Puerto Montt",
  //   comuna: "Puerto Varas",
  //   fechapublicacion: "2024-02-16",
  //   likes: 19,
  // },
  // {
  //   publicacionId: 10,
  //   usuarioId: 110,
  //   titulo: "Servicio de limpieza",
  //   contenido: "Limpieza profunda para hogares y oficinas",
  //   imagen: "imagen10.jpg",
  //   tiposervicio: "limpieza",
  //   emailcontacto: "usuario10@example.com",
  //   telefonocontacto: "+56 9 4444 3333",
  //   ciudad: "Arica",
  //   comuna: "Putre",
  //   fechapublicacion: "2024-02-15",
  //   likes: 16,
  // },
];

export const dataUsuarios = [
  {
    token: '123',
    usuario: {
      usuarioid: 1,
      nombre: 'Juan Pérez',
      email: 'juan@example.com',
      contraseña: '123456',
      ciudad: 'Santiago',
      comuna: 'Providencia',
      direccion: 'Av. Manuel Montt 123',
      fotoperfil: '',
      rol: 'usuario',
    },
  },
  {
    token: '123',
    usuario: {
      usuarioid: 2,
      nombre: 'María Gómez',
      email: 'maria@example.com',
      contraseña: '123456',
      ciudad: 'Valparaíso',
      comuna: 'Viña del Mar',
      direccion: 'Av. España 456',
      fotoperfil: 'imagen2.jpg',
      rol: 'usuario',
    },
  },
  {
    token: '123',
    usuario: {
      usuarioid: 3,
      nombre: 'Carlos Rodríguez',
      email: 'carlos@example.com',
      contraseña: '123456',
      ciudad: 'Concepción',
      comuna: 'Talcahuano',
      direccion: 'Calle Colón 789',
      fotoperfil: 'imagen3.jpg',
      rol: 'usuario',
    },
  },
];
